apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscription-service
  namespace: snooker-livescore
  labels:
    app: subscription-service
    component: data-read
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscription-service
  template:
    metadata:
      labels:
        app: subscription-service
        component: data-ingestion
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      containers:
      - name: subscription-service
        image: astoyanov87/subscription-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: health
        resources:
          limits:
            cpu: "500m"
            memory: "1Gi"
          requests:
            cpu: "200m"
            memory: "512Mi"
        env:
        - name: REDIS_HOST
          value: "redis-master"
        - name: REDIS_PORT
          value: "6379"
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: RABBITMQ_PORT
          value: "5672"
        - name: SMTP_HOST
          value: "maildev"
        - name: SMTP_PORT
          value: "1025"
        livenessProbe:
          httpGet:
            path: /health
            port: health
          initialDelaySeconds: 30
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /health
            port: health
          initialDelaySeconds: 5
          periodSeconds: 10